language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.base.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com/
  - secure: EQdx55TTft190J32wOZQ4FV2xIIi6g5zGGKYZDXXeYxMsEYuR+G3eZNuacAoZNt8JqWhmPljh6LgyfG7MakT+UGM0GqlCE7WWxbVPfV6IxJLXOdkWry41m2mpS8BxVVfntJM4n0lgHZ9nxqrYDprKMdh/T0BrC2oQjbu/1MNpJ7eRZ32BxPJkLjX61XzTeO2W69M6Tnna/Z/WNF8Gak8N2rpe4IqVAyvWTUUZClHsecgo3Dj1Xb2VxcexKLBinp4aJOhn5GOqcXF+Tk5orHA++IKrC+H6pZ4okq5CUWsR9NFI369mJEQIWN4VY35sHZnhoEgH0Fx1rrW83BvxjMZaV67k2RrCdY9pQF4DqcMTJYo+yflztUbjDGC7GpU1qxqwHeJvmgIXHqp8Cgqf/4XESSsBpvluvZ+J4W7Lu6iNtpHrVostPhxQDIOtUz1ITbpaE+eURmtivZoeU6OXOew9R3APEG65COjXUx936Oi1Ts+LH3k7ncumXQVvJJ4Ga1ypGMTCfUz0xteoBAdwVQufZF5LL85zJxyiKTFSPo7EGesJtiUlesUbvmKHekUPfVQljn8ba31A9VzGxrRoR0kkoHxgHCl2SVCgbH0MFAJ0OG2JlLXbsXXI98R6ipdb17e/Gh6iPGxuYQf0TWjOfh8tWzg4DEhkowKiubBnqad3Jw=
  - secure: NMFQ/30d1lJ5oCLVRV7wWNjnYLL/15+KapE+VWVYSZlr1r9BCq8fBYogi5dO0vKoQV9iuuBeNrdSO4x16d9Qfu4I8d8iwWZfTf6eXmGdGclWe74e1sft8jea/jWl/Kr5scfIANt2aJYij5CBNSAxM57ImuFxbcpmHuakhTOjLlMhy/g1pTmEA9yED3+OS8FwjslOJgNZlAC1Y2jLmiblX/xOcDaQdQaJU9D0Vi5LAeKK0V4m1NJ4aK1Medq5zOPuVnA42naripK6qtvtaJpcqirLliuvcYdRLaviEIDvilLwEiXj2edRPk1kk9XkdWnd8a+04rHkZ1wgKwA1RmHSNX9eEGchkyVMuVD3x3sppFWBXvcOoJTauLUY/hoeZrrsOp+TMfO92/bHm4KBZxuLIfD/igRFVpkv8ZArlPWTG6sMurD5UU32Jnc91lDa6OofOIGd2kXl5U9UCyi7WosJ50BTMcjIDSXOl98FcpaHpMl4sSEiD+QXQhhiIjBeoJZekIe/ko5KYT74hOvs4qn1C8u7w26b6q/hk8shJHQQTbSAQgWOxfU2WvQtCtL8j1qlceBEOE4Cf4thn/S0Kj+/H6XyfOSgR/MmkD7cExeTyVp9zBe7sALYms7Yj9p6btNLx3Xu3zy+s9cgH/Nuqy/GcYj93C94rl9Wnplxb8ElZwA=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
