language: node_js
node_js: "5"
before_script: npm install -g wcfutils
script: wcfutils
branches:
  only: master
git:
  depth: 5
env:
  global:
    - IDENTIFIER=com.clanunknownsoldiers.plugin.base.tar
    - FTP_HOST=ftp://thunderstorm.padarom.io
    - secure: "C/jzkV0sWzjI5dxP2HjplgLdHeAbUt/R53r5HrqUMreW9FbaAi3rtXKWbdBH8RCjsgZqtguhEWmTiuOWE+VOjrvEfyzKkezI8Se/3GYA1oN/2Ex9+3eMusgb/ugWYLAZOndpZsTr8PnDkUS5aN1m49OILOw1mTTB3FrFbr//0Otck2oW6NhXkWuE4BeDXZjfip64lwlOQAcgROqTIb3HcBhERYYmwU/bd7IyizGQMfOSicSTdky+W7pszltshitn9pmYlapztqjsFJMX+nb0PdxhvZLViXC75dR5NtKrm/OlBtc8Y/0eM4ySDpu6t8ggqOxSlysc5kmqKL308vVhdNr7gxYV86khspMsoLT6mQJ+SE95+IWOdWLv/9Hyj9zcJTnuUp8g/Svtiw8WTiikqB3TtFJUG5Pi+YIqnwTR7CmsDN4eF28/keQR+TlSj8hSL07SPyZQtOhnnGgTNz4M3MJUfSYEHIFTMyJq90tlLg/DU5OEBWT78H4nNvD2NWapgD3HMzew7lybNTTvHUV4j9eJpu5A4u0swTvg/SmhWGH8QopnGg2SjTbMfN9IbljQo/Tr4ZNE72MSUgG3S6F4Cz4hvRo4YoH+9Zbb2pScq5VJuTz9eHj40eUAHG68dHz1+EOjyc+P7evoPsCSTgzDXPyVWeJUFkL+eTgywctZSaM="
    - secure: "Bb59ofD+p/1YeoUgN17THXgo7/wNY34z/FGyRk7J/j7DEQn7M1iFEJrtaTSjjNiCngvO/5CmWwde8CARF+r/zVXR4KKvHQIYwqLg46ueljOijpZ0PHZ69P/BtGvh36TCFsh2w/DKm8AjDmwsOKsT9Zfnrdxs699SvIRel+aACW7oDl7ucSaOgwFvkAoLBHKqGMqOQxNg2Ul6sd4WgoU0XSxNNX4AFwzIIeb7b12BrMfS5MfVzSPQQ2OrgM5jYDUkEXM7oLMV0xja11ViISh3flXjVZjrQfWMpS8mWTNVOX9mx/Q9BR/qfSKndq63I8cW4pjyjRtNgoOeiGzSaNbH2hTWRdIbo35UBbiY+qGUk+FI0DJ6jYyFWosQm3l5Mtpt4EG++3af6NXJXwp3Z1MhjYJyepzDibGpDR90MkHDjVsYt/bX5IKSnpBpBIRAUHp2bJrIG/aw9RE7o+Ek7NOCZQQNCS1TpBGiXYjoGZ8rUCmElN1SrB9bicxMbN0qNOxoShMI6U8s6oI/025JpRYXhhbJG0N1eLLZeGxAsLF7OJspZZGnfSa+9Gz68A/rXRGipsPqd2D1RvpPFp8IfDhzX8If+Jj7MLOYlb1ksiJlJ3GVHog3gBQ1p+0F41ZrRAAxJT6u6K1oPKSK2/feV3iC0rgzaBau6ALY8lHtTfCiuv0=" 
notifications:
      email: false

after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
