language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.base.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com/
  - secure: XPsEgaT4YD8gaCLAhcLWy5z00v9OAzBLVw+BvIAUpUhzRP4rwcoPlnikhPWk2mBViBG5a2ehRGPZZv6bGnqTW/6sBf6/cdfZ3M4LlZLxACNrXb0esAhIP2WhCrvsb6FF8cJFrcsEwOLUrvcHXvLv46xFjYIlI+XDNDzQW5WIR9f2SFCDWcQibudtY1icRWremeQ57n2EXwZgCTcr/uCEUaWWOJVVMqkTRnvh7Ighc4Q4g/dJXdIfQZHTmS7AitAWxR6ETbrm4XAN24GFFVO0w0ySGvn93oerbKA2nUKxZSloGj7vaN9T5r44v+pru95MBcLqDLbzkxaXIog1t7BMNyU65zmHjOc8f7bdl8TPo/sdIyp43M781kO5vxSqai1GY5D9rua3XR6oS2r1ThJTuARMm/6RzaDtgeskC1RK7VjimBRL7ReAw46gg5o5Crfp/uvQDlUE0jov+is+OmIvRzyFpzN2JX2oCAc09txcCUDHPn0pR+gAYpBIotRuNIL/Dk5sQ4Oz5n9ZmUGvGitPN6dQAR2VxQWDHvbUUntC44IUHeIEmiQEY4/WV7e42FFMJHgpE88atEFSzSWNR8OxhOzgVCRcrliilIKrrQAoMOSAReVNfgSLLOcaKlTRCur0nP6AFS4G1NowbcqF/3r73jYzbAn9agWoZT2ANcW34J0=
  - secure: mTZfbWeLF32vGUg03cmIFvPXdyyAu5cOUOFH1AQTf60y7pLe+jLEv0gMTKThd+njhM8aZ2N0I17NxpKzINjE+PEHiuaPyrInWRgJUL8P75IqgsP7ZceLTA3xhIQ9ErSor4oBbUC1DCOxaxYt6vHT9hnR59DzD1peuxv6jqoxsqcugRa1JA70pe3Hy+qxHnlKVULT/TM1jSj4ZQ9ChZYLpc3CZveqOKd1ymW9CvLYls5GbRvwidI+2zrIyJ1JadsUWBPtRN4gJADRiXU2MQywqWG63zUWkRrrgWMXlrJtJF52RcUfuHr2ZG2C7c0+Xqs1HnMesQCnxhQa5mqJy0lWSW3SYzpP6xfPd1+G+w8fqnvlUbbQJB5xZmN4JekQ4GgF++U7irvriKaVGRepGaa2dDwE4wMF/p8vlEpLrJq1+I5ogIjComTqa/7nbDGAV5PKsso7tWKRNCut4P5dB7RQjH5J0aWc7Fqs+BeVAzbDxmVZzu6dUBri2wM6eSuV+A3kiIVLVIGJjx15VZ1ZYfny5XDd3a7iHzlxE16pJjbS6K+g2qna44aWBxm7LhHFCvugEclQE8lkiPw7UEvQoXcPfiDjv6KUkOa7cORZH3OWckxovxjHhcl7Z/Po2z+C9g5zWt3Xc2MSbwuYufjSGws8YabnIg5jheFG0vypWUG1obg=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
